theme:  jekyll-theme-cayman
title: Rétrospective des modélisations Covid-19 en France
author: Antigone 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Les modélisations mathématiques de la propagation du covid-19 guident depuis bientôt deux ans la mise en place de politiques publiques avec des impacts majeurs sur la vie des français. 
  Ce site vise à rendre publique une évaluation systématique de la fiabilité de ces modélisations, ce qui n'a pas encore été fait. 
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

github:
  is_project_page: false
  
