theme: jekyll-theme-cayman
title: Evaluation de la fiabilité des prédictions sur la propagation du covid-19 en France
author: Antigone 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Les modélisations mathématiques de la propagation du covid-19 ont pris une place prépondérante dans notre société, en guidant la mise en places de restrictions sanitaires. Pourtant, 
  aucune évaluation retrospective de la fiabilité de ces modélisations n'a encore été faite. Ce site vise à remédier à cela et à évaluer systématiquement la fiabilité de ces modélisations. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

github:
  is_project_page: false
  
